import { db } from "./index";
import { customers } from "./schema/customers";

const seedData = [
  {
    firstName: "Jan",
    lastName: "de Vries",
    email: "jan.devries@email.com",
    phone: "+31 6 12345678",
    street: "Hoofdstraat 123",
    city: "Amsterdam",
    postalCode: "1012 AB",
    country: "Nederland",
    company: "Tech Solutions BV",
    notes: "Belangrijke klant, altijd vriendelijk",
  },
  {
    firstName: "Maria",
    lastName: "van der Berg",
    email: "maria.vandenberg@email.com",
    phone: "+31 6 87654321",
    street: "Kerkstraat 45",
    city: "Utrecht",
    postalCode: "3511 BC",
    country: "Nederland",
    company: "Design Studio",
    notes: "Geïnteresseerd in premium services",
  },
  {
    firstName: "Pieter",
    lastName: "Janssen",
    email: "p.janssen@email.com",
    phone: "+31 6 55512345",
    street: "Marktplein 78",
    city: "Rotterdam",
    postalCode: "3011 DE",
    country: "Nederland",
    company: "Janssen & Co",
    notes: "Regelmatige bestellingen, betrouwbare betaler",
  },
  {
    firstName: "Sophie",
    lastName: "Bakker",
    email: "sophie.bakker@email.com",
    phone: "+31 6 99887766",
    street: "Dorpsstraat 12",
    city: "Den Haag",
    postalCode: "2514 FG",
    country: "Nederland",
    notes: "Nieuwe klant, veel potentieel",
  },
  {
    firstName: "Thomas",
    lastName: "Smit",
    email: "thomas.smit@email.com",
    phone: "+31 6 11223344",
    street: "Industrieweg 89",
    city: "Eindhoven",
    postalCode: "5611 HI",
    country: "Nederland",
    company: "Smit Industries",
    notes: "Technische vragen, detail-georiënteerd",
  },
  {
    firstName: "Eva",
    lastName: "Kuipers",
    email: "eva.kuipers@email.com",
    phone: "+31 6 33445566",
    street: "Lindelaan 7",
    city: "Groningen",
    postalCode: "9711 AA",
    country: "Nederland",
    company: "Kuipers Consulting",
    notes: "Vraagt vaak om offertes",
  },
  {
    firstName: "Bram",
    lastName: "Visser",
    email: "bram.visser@email.com",
    phone: "+31 6 77889900",
    street: "Havenstraat 22",
    city: "Haarlem",
    postalCode: "2011 CD",
    country: "Nederland",
    notes: "Betaalt altijd op tijd",
  },
  {
    firstName: "Lotte",
    lastName: "Meijer",
    email: "lotte.meijer@email.com",
    phone: "+31 6 22334455",
    street: "Parklaan 56",
    city: "Arnhem",
    postalCode: "6811 HL",
    country: "Nederland",
    company: "Meijer Events",
    notes: "Organiseert evenementen",
  },
  {
    firstName: "Daan",
    lastName: "de Boer",
    email: "daan.deboer@email.com",
    phone: "+31 6 44556677",
    street: "Boslaan 9",
    city: "Zwolle",
    postalCode: "8011 AB",
    country: "Nederland",
    notes: "Heeft interesse in nieuwe producten",
  },
  {
    firstName: "Sanne",
    lastName: "Mulder",
    email: "sanne.mulder@email.com",
    phone: "+31 6 55667788",
    street: "Stationsweg 3",
    city: "Leiden",
    postalCode: "2312 AT",
    country: "Nederland",
    company: "Mulder Marketing",
    notes: "Vraagt om maandelijkse rapportages",
  },
  {
    firstName: "Rick",
    lastName: "de Groot",
    email: "rick.degroot@email.com",
    phone: "+31 6 66778899",
    street: "Bergweg 14",
    city: "Maastricht",
    postalCode: "6211 AA",
    country: "Nederland",
    notes: "Heeft support nodig voor installatie",
  },
  {
    firstName: "Kim",
    lastName: "Jansen",
    email: "kim.jansen@email.com",
    phone: "+31 6 77889911",
    street: "Veldstraat 88",
    city: "Breda",
    postalCode: "4811 XX",
    country: "Nederland",
    company: "Jansen Retail",
    notes: "Nieuwe winkel geopend",
  },
  {
    firstName: "Niels",
    lastName: "Peeters",
    email: "niels.peeters@email.com",
    phone: "+31 6 88990011",
    street: "Kanaalstraat 5",
    city: "Amersfoort",
    postalCode: "3811 LL",
    country: "Nederland",
    notes: "Vraagt om technische documentatie",
  },
  {
    firstName: "Tessa",
    lastName: "de Jong",
    email: "tessa.dejong@email.com",
    phone: "+31 6 99001122",
    street: "Singel 101",
    city: "Alkmaar",
    postalCode: "1811 AB",
    country: "Nederland",
    company: "De Jong Advies",
    notes: "Komt vaak langs op kantoor",
  },
  {
    firstName: "Joris",
    lastName: "Willems",
    email: "joris.willems@email.com",
    phone: "+31 6 11224455",
    street: "Spoorstraat 17",
    city: "Tilburg",
    postalCode: "5011 AA",
    country: "Nederland",
    notes: "Heeft een groot project lopen",
  },
  {
    firstName: "Lisa",
    lastName: "van Dijk",
    email: "lisa.vandijk@email.com",
    phone: "+31 6 22335566",
    street: "Molenstraat 42",
    city: "Delft",
    postalCode: "2611 BB",
    country: "Nederland",
    company: "Van Dijk Architectuur",
    notes: "Interesse in duurzame materialen",
  },
  {
    firstName: "Mark",
    lastName: "Bakker",
    email: "mark.bakker@email.com",
    phone: "+31 6 33446677",
    street: "Kerkweg 15",
    city: "Gouda",
    postalCode: "2801 CC",
    country: "Nederland",
    notes: "Regelmatige bestellingen",
  },
  {
    firstName: "Anna",
    lastName: "Schouten",
    email: "anna.schouten@email.com",
    phone: "+31 6 44557788",
    street: "Schoolstraat 8",
    city: "Schiedam",
    postalCode: "3111 DD",
    country: "Nederland",
    company: "Schouten & Partners",
    notes: "Vraagt om snelle levering",
  },
  {
    firstName: "Paul",
    lastName: "van der Meer",
    email: "paul.vandermeer@email.com",
    phone: "+31 6 55668899",
    street: "Dorpsweg 33",
    city: "Vlaardingen",
    postalCode: "3131 EE",
    country: "Nederland",
    notes: "Nieuwe klant, veel potentieel",
  },
  {
    firstName: "Emma",
    lastName: "Bos",
    email: "emma.bos@email.com",
    phone: "+31 6 66779900",
    street: "Boslaan 12",
    city: "Spijkenisse",
    postalCode: "3201 FF",
    country: "Nederland",
    company: "Bos Groen",
    notes: "Houdt van natuurlijke producten",
  },
  {
    firstName: "Tim",
    lastName: "de Wit",
    email: "tim.dewit@email.com",
    phone: "+31 6 77880011",
    street: "Witstraat 67",
    city: "Capelle aan den IJssel",
    postalCode: "2901 GG",
    country: "Nederland",
    notes: "Technische vragen",
  },
  {
    firstName: "Julia",
    lastName: "Koning",
    email: "julia.koning@email.com",
    phone: "+31 6 88991122",
    street: "Koninginweg 23",
    city: "Helmond",
    postalCode: "5701 HH",
    country: "Nederland",
    company: "Koning Design",
    notes: "Creatieve klant",
  },
  {
    firstName: "Bas",
    lastName: "van Leeuwen",
    email: "bas.vanleeuwen@email.com",
    phone: "+31 6 99002233",
    street: "Leeuwenstraat 89",
    city: "Oss",
    postalCode: "5341 II",
    country: "Nederland",
    notes: "Betaalt altijd op tijd",
  },
  {
    firstName: "Fleur",
    lastName: "de Bruijn",
    email: "fleur.debruijn@email.com",
    phone: "+31 6 11223344",
    street: "Bruijnlaan 45",
    city: "Roosendaal",
    postalCode: "4701 JJ",
    country: "Nederland",
    company: "De Bruijn Advies",
    notes: "Vraagt om maandelijkse updates",
  },
  {
    firstName: "Ruben",
    lastName: "Smit",
    email: "ruben.smit@email.com",
    phone: "+31 6 22334455",
    street: "Smitweg 78",
    city: "Bergen op Zoom",
    postalCode: "4611 KK",
    country: "Nederland",
    notes: "Heeft een groot project",
  },
  {
    firstName: "Mila",
    lastName: "van den Berg",
    email: "mila.vandenberg@email.com",
    phone: "+31 6 33445566",
    street: "Bergstraat 34",
    city: "Oosterhout",
    postalCode: "4901 LL",
    country: "Nederland",
    company: "Van den Berg Events",
    notes: "Organiseert evenementen",
  },
  {
    firstName: "Lucas",
    lastName: "Jansen",
    email: "lucas.jansen@email.com",
    phone: "+31 6 44556677",
    street: "Jansenlaan 56",
    city: "Waalwijk",
    postalCode: "5141 MM",
    country: "Nederland",
    notes: "Nieuwe klant",
  },
  {
    firstName: "Zoë",
    lastName: "de Vries",
    email: "zoe.devries@email.com",
    phone: "+31 6 55667788",
    street: "Vriesstraat 90",
    city: "Dordrecht",
    postalCode: "3311 NN",
    country: "Nederland",
    company: "De Vries Marketing",
    notes: "Interesse in digitale marketing",
  },
  {
    firstName: "Noah",
    lastName: "Bakker",
    email: "noah.bakker@email.com",
    phone: "+31 6 66778899",
    street: "Bakkerweg 12",
    city: "Zoetermeer",
    postalCode: "2711 OO",
    country: "Nederland",
    notes: "Vraagt om technische ondersteuning",
  },
  {
    firstName: "Luna",
    lastName: "van der Heijden",
    email: "luna.vanderheijden@email.com",
    phone: "+31 6 77889900",
    street: "Heijdenlaan 67",
    city: "Nieuwegein",
    postalCode: "3431 PP",
    country: "Nederland",
    company: "Van der Heijden Consultancy",
    notes: "Expertise in IT",
  },
];

async function seed() {
  try {
    console.log("🌱 Seeding database...");

    // Clear existing data
    await db.delete(customers);

    // Insert seed data
    const insertedCustomers = await db
      .insert(customers)
      .values(seedData)
      .returning();

    console.log(`✅ Seeded ${insertedCustomers.length} customers`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seed();
